import { Geist, Geist_Mono , Roboto, Allura ,Playfair_Display , Comic_Neue , Rubik_Dirt , Press_Start_2P} from "next/font/google";
import "./globals.css";
import {myFont} from "./font";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight:["500","600"]
});

const allura = Allura({
  subsets: ["latin"],
  weight:["400"]
});
const playfair_displey = Playfair_Display({
  subsets: ["latin"],
  weight:["400"]
});
const comic = Comic_Neue({
  subsets: ["latin"],
  weight:["400"]
});
const rubikDirt = Rubik_Dirt({ subsets: ["latin"], weight: "400" });

const pressStart = Press_Start_2P({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
